services:
  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER?Variable not set}
      DB_PASSWORD: ${DB_PASSWORD?Variable not set}
      DB_NAME: "*"  # Permite conexão a qualquer database
      POOL_MODE: transaction
      AUTH_TYPE: scram-sha-256
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 30
    ports:
      - "6543:5432"
    depends_on:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure