services:
  postgres:
    image: postgres:15-alpine
    command: [
      "postgres",
      "-c", "max_connections=200",
      "-c", "listen_addresses=*",
      "-c", "shared_buffers=256MB",
      "-c", "effective_cache_size=1GB",
      "-c", "work_mem=4MB"
    ]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_DB_NAMES=${DB_NAMES?Variable not set}
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data_new: